services:
  model-service:
    image: ghcr.io/doda2025-team22/model-service:canary
    restart: unless-stopped
    environment:
      - BACKEND_PORT=8081
      - OUTPUT_DIR=/app/output
    volumes:
      - ./model:/app/output
    ports:
      - "8081:8081"
    networks:
      - sms-app-network

  app-service:
    image: ghcr.io/doda2025-team22/app:canary
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=8080
      - MODEL_HOST=http://model-service:8081
    ports:
      - "8080:8080"
    networks:
      - sms-app-network

networks:
  sms-app-network:
    driver: bridge
