services:
  model-service:
    image: ghcr.io/doda2025-team22/model-service:${CONTAINER_TAG}
    restart: unless-stopped
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - OUTPUT_DIR=${OUTPUT_DIR}
    volumes:
      - ./model:/app/output
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - sms-app-network

  app-service:
    image: ghcr.io/doda2025-team22/app:${CONTAINER_TAG}
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - MODEL_HOST=${MODEL_HOST}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - sms-app-network

networks:
  sms-app-network:
    driver: bridge
