services:
  model-service:
    image: ghcr.io/doda2025-team22/model-service:latest
    environment:
      - BACKEND_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - sms-app-network

  app-service:
    image: ghcr.io/doda2025-team22/app:latest
    environment:
      - PORT=8080
      - MODEL_HOST=http://model-service:8081
    ports:
      - "8080:8080"
    networks:
      - sms-app-network

networks:
  sms-app-network:
    driver: bridge
