# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: team22-ingress
# spec:
#   {{- if .Values.ingress.className }}
#   ingressClassName: {{ .Values.ingress.className | quote }}
#   {{- end }}
#   rules:
#     - host: "{{ .Values.global.stableSubdomain }}.{{ .Values.global.domain }}"
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: app-svc
#                 port:
#                   number: {{ .Values.app.port }}
#     - host: "{{ .Values.global.prereleaseSubdomain }}.{{ .Values.global.domain }}"
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: app-svc
#                 port:
#                   number: {{ .Values.app.port }}
# {{- if .Values.monitoring.enabled }}
#     - host: "prometheus.{{ .Values.global.domain }}"
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: team22-kube-prometheus-sta-prometheus
#                 port:
#                   number: 9090
#     - host: "grafana.{{ .Values.global.domain }}"
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: team22-app-grafana
#                 port:
#                   number: 80
# {{- end }}
