apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelservice
spec:
  replicas: {{ .Values.modelservice.replicaCount }}
  selector:
    matchLabels:
      app: modelservice
  template:
    metadata:
      labels:
        app: modelservice
    spec:
      containers:
        - name: modelservice
          image: "{{ .Values.modelservice.image.repository }}:{{ .Values.modelservice.image.tag }}"
          ports:
            - containerPort: {{ .Values.modelservice.port }}
          env:
            - name: API_TIMEOUT_MS
              value: "{{ .Values.config.appConfig.API_TIMEOUT_MS }}"
            - name: FEATURE_FLAG_TEST
              value: "{{ .Values.config.appConfig.FEATURE_FLAG_TEST }}"