apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: ratelimit
    descriptors:
      - key: PATH
        value: "/sms"
        rate_limit:
          unit: minute
          requests_per_unit: 10
#      - key: PATH
#        rate_limit:
#          unit: minute
#          requests_per_unit: 1000
