---
# Service for App (Frontend)
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: app
spec:
  type: ClusterIP
  selector:
    app: app-service
  ports:
    - name: http
      port: {{ .Values.app.stable.port }}
      targetPort: {{ .Values.app.stable.port }}
---
# Service for Model Service (Backend)
apiVersion: v1
kind: Service
metadata:
  name: model-svc
  labels:
    app: modelservice
spec:
  type: ClusterIP
  selector:
    app: model-service
  ports:
    - name: http
      port: {{ .Values.modelservice.stable.port }}
      targetPort: {{ .Values.modelservice.stable.port }}