# Create a Service for the fronend
#! Still needs to communicate with the backend service apparently. Try to find the docs for it.
apiVersion: v1
kind: Service
metadata:
    name: app-svc
spec:
    type: ClusterIP
    selector:
        app: app-service
    ports:
        -   port: {{ .Values.app.port }} # Exposed Port
            targetPort: {{ .Values.app.port }} # forward port

---
# Create a Service for the backend
apiVersion: v1
kind: Service
metadata:
    name: model-svc
spec:
    type: ClusterIP
    selector:
        app: model-service
    ports:
        -   port: {{ .Values.modelservice.port }} # Exposed Port
            targetPort: {{ .Values.modelservice.port }} # forward port