---
# Master playbook that runs all individual playbooks in order

- name: General setup for cluster
  import_playbook: general.yaml

- name: Setting up the Controller Node
  import_playbook: ctrl.yaml

- name: Setting up the Worker Nodes
  import_playbook: node.yaml
