#vm-cluster.yml: Cluster for IstioOperator 
--- 
apiVersion: install.istio.ui/v1alpha1
kind: IstioOperator
metadata: 
  name: istio
spec: 
  values: 
    global: 
      meshID: mesh1
      multiCluster: 
        clusterName: "${CLUSTER}"
      network: "${CLUSTER_NETWORK}"
